export const REQUEST_FETCH_MEETINGS  = "REQUEST_FETCH_MEETINGS"
export const RECEIVE_MEETINGS  = "RECEIVE_MEETINGS"
export const FETCH_MEETINGS_ERROR  = "FETCH_MEETINGS_ERROR"

export const REQUEST_FETCH_MEETING  = "REQUEST_FETCH_MEETING"
export const RECEIVE_MEETING  = "RECEIVE_MEETING"
export const FETCH_MEETING_ERROR  = "FETCH_MEETING_ERROR"

export const REQUEST_CREATE_MEETING  = "REQUEST_CREATE_MEETING"
export const MEETING_CREATED  = "MEETING_CREATED"
export const CREATE_MEETING_ERROR  = "CREATE_MEETING_ERROR"

export const REQUEST_CREATE_HIGHLIGHT  = "REQUEST_CREATE_HIGHLIGHT"
export const HIGHLIGHT_CREATED  = "HIGHLIGHT_CREATED"
export const CREATE_HIGHLIGHT_ERROR  = "CREATE_HIGHLIGHT_ERROR"
